### ISSUE TITLE
Moedinha ETC perdida 

### ISSUE THREAD

**Issue by Bolsa-BOMS** [ethereumclassic/tweets-etc_network#140]
Como resgatar uma moedinha no bloco e colocar na carteira?
Por favor comprei 1 ETC e ficou perdida no bloco, não consigo uma carteira que me dê a opção de buscar ela para colocar dentro da carteira!
How to redeem a coin in the block and put it in the wallet?
Please I bought 1 ETC and it got lost on the block, I can't find a wallet that gives me the option to get it to put it inside the wallet!

**Comment by TheCrowbill** [comment]
Since it does not directly concern the ETC_Network Twitter account and several months of inactivity have passed, I am closing this issue.
