### ISSUE TITLE
Would it be possible to have the same content for tweets to go to a Mastodon account?

### ISSUE THREAD

**Issue by w1g0** [ethereumclassic/tweets-etc_network#22]
**What’s missing?**
There's nothing missing, just a proposal for enhancement

Posting the same message as on Twitter on Mastodon
**Why?**
To have more widespread news

Centralization of the message
**Alternatives you tried**
Mastodon

**Comment by gitr0n1n** [comment]
Yes i believe there is a twitter to mastodon app. So we would post on twitter and it would also post on mastodon. Search you'll find many solutions for this. Let me know what you think would be best and we can configure that bridge.

**Comment by w1g0** [comment]
Ok that Twitter to Mastodon app sound like a good start. Question is what will happen when Twitter bans the account for whatever reason, but we can find a solution if that would ever happen. Unless anyone else has another objection?
Currently I hold the @ethereum_classic account on https://mastodon.social/web/@Ethereum_Classic
If we ever would want to create our own server instance, that could be set up by the ETCcooperation? @bobsummerwill

**Comment by IstoraMandiri** [comment]
Adding mastodon would require some significant rework of the repo including updating a new API and being able to tell the app whether the `tweet` or `toot` should go to mastodon.

As such @gitr0n1n 's suggestion of a bot is the best stop gap until this get's implemented, but given the audience, is lower priority than other issues.

**Comment by w1g0** [comment]
> Adding mastodon would require some significant rework of the repo including updating a new API and being able to tell the app whether the `tweet` or `toot` should go to mastodon.
> 
> As such @gitr0n1n 's suggestion of a bot is the best stop gap until this get's implemented, but given the audience, is lower priority than other issues.

A bot always uses the same login credentials and leads to centralization, when an account is compromised all accounts further down the chain are affected. This is more important than you estimate, we need more developers on this project. The more you go down the pyramid, the more robust it needs to be. Ideally you have a multi-sig at the top but I haven't seen software yet supporting that infrastructure.

**Comment by bobsummerwill** [comment]
If we are forced into hosting stuff ourselves we can do that yet, @w1g0
