### ISSUE TITLE
Insights section has interference data from the original repo

### ISSUE THREAD

**Issue by w1g0** [ethereumclassic/tweets-etc_network#37]

**Comment by IstoraMandiri** [comment]
@w1g0 could you explain this one? Thanks!

**Comment by w1g0** [comment]
Sure, I noticed that the insights have all the data of the original repo. It might be useful to have a way to reset it. If we want to see contributions from the original repo go there to see the contributors. Also the activity line starts from way before we started this sibling.
![2022-09-24_10h39_21](https://user-images.githubusercontent.com/67763069/192089106-2b0976f5-2a33-4de4-b729-d51a40598645.png)

**Comment by IstoraMandiri** [comment]
We can get rid of this but I'll need to nuke the whole repo including the current tweets.

If / when we migrate to @eth_classic, we should use that as an opportunity to do so.
