### ISSUE TITLE
Migrate to eth_classic

### ISSUE THREAD

**Issue by IstoraMandiri** [ethereumclassic/tweets-etc_network#82]
With the recent drama we now have the opportunity to link this system up with the new handle, and create a new repo with a fresh tweet folder.

In the meantime can/should keep this repo as a backup and for experimenting / staging new updates.  

Rel: #70 #37

**Comment by w1g0** [comment]
Migrate or post the same on both accounts?

**Comment by IstoraMandiri** [comment]
We'll have to separate repos with similar but slightly different rules.

`eth_classic` can be the main one with more strict rules (perhaps requiring 2 approvals), and `etc_network` can remain here as a more edgy / experimental / staging environment ? 

We can rename the repos to:

- tweets-eth_classic
- tweets-etc_network

cc: @gitr0n1n @bobsummerwill

**Comment by bobsummerwill** [comment]
Sounds good, @IstoraMandiri.   Let's go :-)

**Comment by w1g0** [comment]
I agree with @bobsummerwill 🚀
